name: Sync to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configure a user identity for Git
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
          # Push directly to the Hugging Face Space repository URL
          git push --force https://user:${HF_TOKEN}@huggingface.co/spaces/PrajwalKulkarni/vehicleTracking main